services:
  backend:
    image: iamsergiocampbell/ree-view-backend:1.0.0
    ports:
      - '5001:5001'
    environment:
      PORT: 5001
      CORS_ORIGINS: http://localhost:5173,http://localhost:80
      MONGODB_URI: ${MONGODB_URI:-mongodb://mongo:27017/energy-balance}
      REE_API_URL: https://apidatos.ree.es/es/datos/balance/balance-electrico
      REE_FRONTERAS_API_URL: https://apidatos.ree.es/es/datos/balance/todas-fronteras-fisicos-programados
      REE_API_URL_ERROR: https://apidatos.ree.es/invalid-endpoint
    depends_on:
      - mongo
    restart: always
    networks:
      - app-network

  frontend:
    image: iamsergiocampbell/ree-view-frontend:1.0.0
    restart: always
    expose:
      - '3001'
    environment:
      - VITE_API_URL=/graphql
      - NODE_ENV=production
      - PORT=3001
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: energy-balance
    volumes:
      - mongo-data:/data/db
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/energy-balance --quiet
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
  npm_network:
    external: true